[[meta-information]]
= Meta information


[#218]
== {MUST} contain API meta information
[yellow-background]#API specifications must contain the following Open API meta information
to allow for API management:#

- [yellow-background]*#/info/title* as (unique) identifying, functional descriptive name of the API
- [yellow-background]*#/info/version* to distinguish API specifications versions following
  <<116, semantic rules>>
- [yellow-background]*#/info/description containing a proper description of the API*
- [yellow-background]*#/info/contact/{name,url,email}* containing the responsible team

Following Open API extension properties *must* be provided in addition:

- [yellow-background]*/info/x-api-id* unique identifier of the API (<<215, see rule 215>>)
- [yellow-background]*/info/x-audience* intended target audience of the API (<<219, see rule 219>>)


[#116]
== {MUST} use semantic versioning

Open API allows to specify the API specification version in
`/info/version`. To share a common semantic of version information we
expect API designers to comply to http://semver.org/spec/v2.0.0.html[
Semantic Versioning 2.0] rules `1` to `8` and `11` restricted to
[yellow-background]#the format <MAJOR>.<MINOR>.<PATCH> for versions# as follows:

* Increment the **MAJOR** version when you make incompatible API changes
after having aligned this changes with consumers,
* Increment the **MINOR** version when you add new functionality in a
backwards-compatible manner, and
* Optionally increment the **PATCH** version when you make
backwards-compatible bug fixes or editorial changes not affecting the
functionality.

*Additional Notes:*

* *Pre-release* versions (http://semver.org#spec-item-9[rule 9]) and
*build metadata* (http://semver.org#spec-item-10[rule 10]) must not
be used in API version information.
* While patch versions are useful for fixing typos etc, API designers
are free to decide whether they increment it or not.
* API designers should consider to use API version `0.y.z`
(http://semver.org/#spec-item-4[rule 4]) for initial API design.

Example:

[source,yaml]
----
openapi: 3.0.1
info:
  title: Parcel Service API
  description: API for <...>
  version: 1.3.7
  <...>
----


[#215]
== {MUST} provide API identifiers

#Each API specification must be provisioned with a globally unique and
immutable API identifier.# The API identifier is defined in the `info`-block
of the Open API specification and must conform to the following definition:

[source,yaml]
----
/info/x-api-id:
  type: string
  format: urn
  pattern: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$
  description: |
    Mandatory globally unique and immutable API identifier. The API
    id allows to track the evolution and history of an API specification 
    as a sequence of versions.
----

API specifications will evolve and any aspect of an Open API specification 
may change. We require API identifiers because we want  to support API clients
and providers with API lifecycle management features, like change trackability
and history or automated backward compatibility checks. The immutable API
identifier allows the identification of all API specification versions of an
API evolution. By using  <<116, API semantic version information>> or <<192,
API publishing date>> as order criteria you get the *version* or
*publication history* as a sequence of API specifications. 

*Note*: While it is nice to use human readable API identifiers based on
self-managed URNs, [yellow-background]#it is recommend to stick to UUIDs# to relief API designers
from any urge of changing the API identifier while evolving the API. Example:

[source,yaml]
----
openapi: 3.0.1
info:
  x-api-id: d0184f38-b98d-11e7-9c56-68f728c1ba70
  title: Parcel Service API
  description: API for <...>
  version: 1.5.8
  <...>
----


[#219]
== {MUST} provide API audience

Each API must be classified with respect to the intended target *audience*
supposed to consume the API, to facilitate differentiated standards on APIs
for discoverability, changeability, quality of design and documentation, as
well as permission granting. We differentiate the following API audience
groups with clear organisational and legal boundaries:

[yellow-background]#*company-internal*#::
  The API consumers with this audience are restricted to applications owned
  by Unifly
[yellow-background]#*external-partner*#::
  The API consumers with this audience are restricted to applications of
  business partners of the company owning the API and the company itself.
[yellow-background]#*external-public*#::
  APIs with this audience can be accessed by anyone with Internet access.

*Note:* a smaller audience group is intentionally included in the wider group
and thus does not need to be declared additionally.

The API audience is provided as API meta information in the `info`-block of
the Open API specification and must conform to the following specification:

[source,yaml]
----
/info/x-audience:
  type: string
  x-extensible-enum:
    - company-internal
    - external-partner
    - external-public
  description: |
    Intended target audience of the API. Relevant for standards around
    quality of design and documentation, reviews, discoverability,
    changeability, and permission granting.
----

[yellow-background]#*Note:* Exactly *one audience* per API specification is allowed.# For this
reason a smaller audience group is intentionally included in the wider group
and thus does not need to be declared additionally. If parts of your API have
a different target audience, we recommend to split API specifications along
the target audience — even if this creates redundancies
(https://apis.unifly.net/redirect/85ee93a3-7a78-4461-8bf1-08ffdaebcd18[rationale
(internal link)]).

Example:

[source,yaml]
----
openapi: 3.0.1
info:
  x-audience: company-internal
  title: Parcel Helper Service API
  description: API for <...>
  version: 1.2.4
  <...>
----

For details and more information on audience groups see the
https://apis.unifly.net/redirect/85ee93a3-7a78-4461-8bf1-08ffdaebcd18[
API Audience narrative (internal link)].
