[[appendix-tooling]]
[appendix]
= Tooling

This is not a part of the actual guidelines, but might be helpful for following them.
Using a tool mentioned here doesn't automatically ensure you follow the guidelines.


[[api-first-integrations]]
== API first integrations

The following frameworks were specifically designed to support the API First
workflow with Open API YAML files (sorted alphabetically):

* *https://github.com/unifly/connexion[Connexion]:*
  Open API First framework for Python on top of Flask
* *https://github.com/unifly-stups/friboo[Friboo]:*
  utility library to write microservices in Clojure with support for Swagger and OAuth
* *https://github.com/unifly/api-first-hand[Api-First-Hand]:*
  API-First Play Bootstrapping Tool for Swagger/Open API specs
* *https://github.com/swagger-api/swagger-codegen[Swagger Codegen]:*
  template-driven engine to generate client code in different languages by
  parsing Swagger Resource Declaration
* *https://github.com/unifly-stups/swagger-codegen-tooling[Swagger Codegen Tooling]:*
  plugin for Maven that generates pieces of code from Open API specification
* *https://github.com/unifly/intellij-swagger[Swagger Plugin for IntelliJ IDEA]:*
  plugin to help you easily edit Swagger specification files inside IntelliJ IDEA

The Swagger/Open API homepage lists more
http://swagger.io/open-source-integrations/[Community-Driven Language
Integrations], but most of them do not fit our API First approach.


[[support-libraries]]
== Support libraries

These utility libraries support you in implementing various parts of our
RESTful API guidelines (sorted alphabetically):

* *https://github.com/unifly/problem[Problem]:*
  Java library that implements application/problem+json
* *https://github.com/unifly/problem-spring-web[Problems for Spring Web MVC]:*
  library for handling Problems in Spring Web MVC
* *https://github.com/unifly/jackson-datatype-money[Jackson Datatype Money]:*
  extension module to properly support datatypes of javax.money
* *https://github.com/unifly/tracer[Tracer]:*
  call tracing and log correlation in distributed systems
* *https://github.com/unifly/twintip-spring-web[TWINTIP Spring Integration]:*
  API discovery endpoint for Spring Web MVC

